name: Update Scalar API Reference v3

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          lfs: true
          token: ${{ steps.generate-token.outputs.token }}
          ref: v3

      - name: Get latest version from npm
        id: get_version
        run: |
          latest=$(npm view @scalar/api-reference version)
          echo "Latest version: $latest"
          echo "version=$latest" >> $GITHUB_OUTPUT

      - name: Read current version
        id: read_current
        run: |
          version_file="scalar/scalar-version.txt"
          if [[ -f "$version_file" ]]; then
            current=$(cat "$version_file")
          else
            current="none"
          fi
          echo "Current version: $current"
          echo "current=$current" >> $GITHUB_OUTPUT

      - name: Skip if version is the same
        if: steps.get_version.outputs.version == steps.read_current.outputs.current
        run: |
          echo "Already up to date."
          exit 0

      - name: Download latest scalar.min.js
        run: |
          curl -L "https://cdn.jsdelivr.net/npm/@scalar/api-reference" -o scalar/scalar.min.js
          echo "${{ steps.get_version.outputs.version }}" > scalar/scalar-version.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "Update Scalar API Reference to v${{ steps.get_version.outputs.version }}"
          committer: yoketh[bot] <1400162+yoketh[bot]@users.noreply.github.com>
          title: "Update Scalar API Reference to v${{ steps.get_version.outputs.version }}"
          body: "This PR updates `scalar.min.js` to the latest version of the Scalar API Reference."
          branch: update-scalar-${{ steps.get_version.outputs.version }}-v3
          delete-branch: true
          base: v3
          add-paths: |
            scalar/scalar.min.js
            scalar/scalar-version.txt
          labels: |
            🤖 Dependencies
          reviewers: yokeTH
